django/rashin/apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('header', views.introductionView, name='introduction'),
    # # path('main_img', views.main_img, name='main_img'),
    # path('logo', views.nav, name='nav'),
    # path('download_cv', views.download_cv, name='download_cv'),
    # path('contact_form', views.contact_form, name='contact_form'),
    # path('footer', views.footer, name='footer'),

    # serializer
    path('info', views.introductionSerView.as_view(), name='info'),
    path('about', views.AboutSerView.as_view(), name='about'),
    path('social', views.socialSerView.as_view(), name='social'),
    path('contact', views.ContactAPI.as_view(), name='contact'),

]
    

django/rashin/rashin/urls.py
from django.contrib import admin
from django.urls import path, include
from theme.views import change_theme
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    path('',include('apps.main.urls', namespace='main')),
    path('faicon/', include('faicon.urls')),
    path('admin/', admin.site.urls),
    path('service',include('apps.service.urls', namespace='service')),
    path('skill/', include('apps.skill.urls', namespace='skill')),
    path('project/',include('apps.project.urls', namespace='project')),
    path('blog',include('apps.blog.urls', namespace='blog')),
    path('switch_theme', change_theme, name='change-theme'),
    
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        'render_icon_list_modal/',
        TemplateView.as_view(
            template_name='faicon_modal.html'
        ),
        name='faicon-modal'
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# handler404 = "django_404_project.views.error_403"
# handler404 = 'apps.main.views.error_404'

django/rashin/templates/partials/footer.html
{% comment %} footer {% endcomment %}
{% if social_media %}
<div   class="  max-w-[90%]  mx-auto mt-14">
    



    <div class="pb-16 gap-5 flex  justify-center">
        <a title="Google, Public domain, via Wikimedia Commons" href= mailto:{{social_media.email}} >
            <img width="32" alt="Gmail icon (2020)" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gmail_icon_%282020%29.svg/32px-Gmail_icon_%282020%29.svg.png">
        </a>
        <a target=”_blank” title="GitHub, MIT &lt;http://opensource.org/licenses/mit-license.php&gt;, via Wikimedia Commons" href={{social_media.gitHub}}>
            <img width="32" alt="Octicons-mark-github" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/64px-Octicons-mark-github.svg.png">
            
        </a>
        <a target=”_blank” title="LinkedIn, Public domain, via Wikimedia Commons" href={{social_media.linkedin}}>
            <img width="32" alt="LinkedIn logo initials" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/64px-LinkedIn_logo_initials.png">
            
        </a>



    </div>

    
</div>

{% endif %}

django/rashin/templates/partials/introduction.html
{% load static %}

<div dir="ltr" class="max-w-[95%]  ">
    {% if Intro %}
    <div  class=" ">          
        <!-- left -->
        <div class=" grow md:mt-10  relative dark:m-0">
            <span class=" mt-12 inline-block font-OpenSansSemiBold text-sm text-light-blue dark:text-white">Hi
                i'am</span>
            <h1 class=" font-OpenSansExtraBold text-4xl text-light-blue dark:text-white">Rashin <span
                    class=" text-blue-500 dark:text-dark-blue">Latify</span> </h1>
            <p class=" mb-3 max-w-[90%] text-justify mt-3 font-OpenSansRegular text-sm text-light-blue dark:text-white">
                    {{Intro.description}}                
            </p>
            
                
        </div>

    </div>
    {% else %}

    {% comment %} <h1 class=" animate__animated animate__heartBeat text-5xl text-center  font-RobotoRegular text-blue-500 dark:text-dark-blue">Convert your CV to a awesome website simply!</h1> {% endcomment %}
    

<div class=' items-center   bg-gradient-to-br'>
    <div class="relative w-full ">
        <div class="absolute-center">
            <svg class="circle-svg" viewBox="0 0 500 500">
                <defs>
                    <path d="M50,250c0-110.5,89.5-200,200-200s200,89.5,200,200s-89.5,200-200,200S50,360.5,50,250"
                        id="textcircle_top">
                        <animateTransform attributeName="transform" begin="0s" dur="20s" type="rotate" from="0 250 250"
                            to="360 250 250" repeatCount="indefinite" />
                    </path>
                </defs>
                <text class="circle-text" dy="70" textLength="1220">
                    <textPath xlink:href="#textcircle_top">
                        Convert your CV to a awesome website simply!

                    </textPath>
                    
                </text> 
            </svg>
            
        </div>
        <div class="absolute-center">
            <div class="showreels-div">
                <video class="showreels-video object-cover" loop autoplay muted>
                    
                    {% comment %} <source src='https://github.com/ahampriyanshu/gfg/raw/main/media/showreel.mp4' type="video/mp4" /> {% endcomment %}
                    {% comment %} <source src='https://github.com/rashin-L/personal-web/raw/main/introduction.mp4' type="video/mp4" /> {% endcomment %}
                    <source src='static/media/view.mp4' type="video/mp4" />
                    <p>Please Update Your Browser</p>
                </video>
                <img
                    alt="play"
                    class="showreels-btn"
                    src='https://github.com/ahampriyanshu/gfg/raw/main/media/play.png'
                />
            </div>
                {% comment %} <a class=" text-blue-500 dark:text-dark-blue text-3xl relative top-14 font-OpenSansSemiBold left-15" href="http://127.0.0.1:8000/admin/">start</a> {% endcomment %}
                <div
            class="start rounded-full bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg  text-center   md:mt-0 w-[7.6rem] h-[2.4rem]  md:w-32 md:h-10">
            <a href="http://127.0.0.1:8000/admin/" class=" z-20 align-[-webkit-baseline-middle]   text-white font-RobotoRegular text-sm md:align-[-webkit-baseline-middle]  md:text-base font-bold" href="{% url 'main:download_cv' %}" >Start</a>
            <button  data-collapse-toggle="navbar-sticky" type="button" class="  flex  p-4 relative -left-3 text-sm text-gray-500 rounded-lg md:hidden  " aria-controls="navbar-sticky" aria-expanded="false">
                <span  class="sr-only relative -left-12">Open main menu</span>
                <svg  class="w-6 h-6 " aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            </button>
        </div>  
                
                {% comment %} <a href="http://127.0.0.1:8000/admin/" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-xl px-5 py-2.5  relative top-14 ri dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Start</a> {% endcomment %}
        </div>
    </div>
</div>
<style>
        .showreels-btn {
        width: 25%;
        height: 25%;
        display: block;
        margin: 0;
        position: absolute;
        top: 50%;
        left: 55%;
        -ms-transform: translate(-55%, -50%);
        transform: translate(-55%, -50%);
    }
    
    .showreels-div:hover .showreels-video {
        display: block;
    }
    
    .showreels-div:hover .showreels-btn {
        display: none;
    }
    
        .circle-text {
        font-size: 24px;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 10px;
        fill: #333;
    }
    
    .showreels-div {
        height: 300px;
        width: 300px;
        border-radius: 100%;
        top: 1rem;
    position: relative;
    }
    .start{
        left: 5rem;
        top: 5rem;
        position: relative;
    }
    
    .showreels-video {
        border-radius: 100%;
        width: 100%;
        height: 100%;
        display: none;
        
    }
    
        .circle-svg {
        height: 600px;
        width: 600px;
    }
    .absolute-center {
        margin: 0;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
 
</style>
{% endif %}

</div>

django/rashin/templates/partials/main_img.html
{% load static %}




{% comment %} change-theme {% endcomment %}

<a class="absolute top-3 right-3 z-40" href="{% url 'change-theme' %}">
{% if is_dark_theme %}
<svg class=" inline-block   w-8 h-8  text-white   ">
    <use xlink:href="#moon"></use>
</svg>
{% else %}
<svg class=" inline-block w-8 h-8  text-white   ">
    <use xlink:href="#sun"></use>
</svg>
{% endif %}
</a> 

{% if edit_intro_img %}

<div style="background-image: url({% static edit_intro_img %} );"  class="   bg-no-repeat bg-cover bg-center backdrop-blur-sm rounded-[15rem] rounded-tr-lg rounded-bl-[20rem]  absolute -right-[1rem] -top-[3rem]
    w-[15rem] h-[15rem] sm:w-[20rem] sm:h-[20rem]  ">
</div>
{% endif %}
{% comment %} {{Intro.main_img}} {% endcomment %}

django/rashin/templates/partials/nav.html
{% load static %}
{% load static tailwind_tags %}
{% if is_dark_theme %}

<div>
<div class='mb-10 '>
    <img src="{% static edit_intro_logo %} " width='100' alt="" style="filter: invert(100%) sepia(0%) saturate(0%) hue-rotate(338deg) brightness(100%) contrast(103%);">

</div>


{% else %}

<div class="mb-10 ">
    
    <img src="{% static edit_intro_logo %}" width='100' alt="" style="filter: invert(36%) sepia(23%) saturate(761%) hue-rotate(154deg) brightness(88%) contrast(87%);">

</div>
{% endif %}

{% if Intro   %}
<nav class=" flex  mx-auto  ">

    <div class="flex md:order-2">
        <div
            class="rounded-full bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg  text-center   md:mt-0 w-[7.6rem] h-[2.4rem]  md:w-32 md:h-10">
            <a class=" z-20 align-[-webkit-baseline-middle]   text-white font-RobotoRegular text-sm md:align-[-webkit-baseline-middle]  md:text-base font-bold" href="{% url 'main:download_cv' %}" >Download CV</a>
            <button onclick="toggle()" data-collapse-toggle="navbar-sticky" type="button" class="  flex  p-4 relative -left-3 text-sm text-gray-500 rounded-lg md:hidden  " aria-controls="navbar-sticky" aria-expanded="false">
                <span  class="sr-only relative -left-12">Open main menu</span>
                <svg  class="w-6 h-6 " aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            </button>
        </div>  
    </div>
    


    <div id="menu" class="   absolute top-[12rem] lg:static z-40   rounded-md md:bg-none items-center justify-between hidden  md:flex md:w-auto md:order-1 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg md:shadow-none" id="navbar-cta">
        <ul class="flex flex-col font-medium p-4 md:p-0   rounded-lg  md:flex-row md:space-x-8 md:mt-0  child:font-RobotoRegular text-l 
        child: text-white child:md:text-light-blue child:md:dark:text-white  child:font-bold 
        ">
            <li>
                <a href="/" class="hover:text-blue-500 hover:dark:text-dark-blue block py-2 pl-3 md:pl-0 pr-4  rounded md:bg-transparent " aria-current="page">Home</a>
            </li>
            <li>
                <a href="#" class="hover:text-blue-500 hover:dark:text-dark-blue block py-2 pl-3 pr-4   ">Projects</a>
            </li>
            <li>
                <a href="#skill" class="hover:text-blue-500 hover:dark:text-dark-blue block py-2 pl-3 pr-4   ">Skills</a>
            </li>
            <li>
                <a href="#service" class="hover:text-blue-500 hover:dark:text-dark-blue block py-2 pl-3 pr-4  ">Services</a>
            </li>
            <li>
                <a href= "{% url 'main:contact' %}" class="hover:text-blue-500 hover:dark:text-dark-blue block py-2 pl-3 pr-4  ">Contact</a>
            </li>
        </ul>
    </div>
</nav>
{% endif %}

</div>